spring:
  application:
    name: flight-ms
  profiles:
    include:
      - db
      - common
  security:
    jwt-secret-key: eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0

---
server:
  port: 8081
user-client:
  url: http://localhost:8083/api/v1/users