application:
  token:
    confirmation:
      expiration-time: 86400
      password-reset-expiration-time: 3600



spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration