spring:
  application:
    name: notification-ms

  profiles:
    include:
     - email
     - db

  security:
    jwt-secret-key: eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0eW91ci0yNTYtYml0LXNlY3JldHlvdXItMjU2LWJpdC1zZWNyZXR5b3VyLTI1Ni1iaXQtc2VjcmV0
server:
  port: 8090
